#!/bin/sh

# Icons
ICON_DIM=""
ICON_BRIGHT=""
ICON_DEFAULT=""

BACKLIGHT_PERCENTAGE=$(xbacklight)
BACKLIGHT_PERCENTAGE=${BACKLIGHT_PERCENTAGE%.*}


#if [ $BACKLIGHT_PERCENTAGE -ge 0 ] && [ $BACKLIGHT_PERCENTAGE -lt 50 ]; then
#	ICON=$ICON_DIM
#elif [ $BACKLIGHT_PERCENTAGE -ge 50 ] && [ $BACKLIGHT_PERCENTAGE -le 100 ]; then
#	ICON=$ICON_BRIGHT
#fi
	
echo $ICON_DEFAULT $BACKLIGHT_PERCENTAGE%
