#Setup XRDB
xrdb $XDG_CONFIG_HOME/xorg/Xresources

#Attempt to connect to all bluetooth devices 
exec ~/.scripts/bluetooth.sh &

#Start xautolock
xautolock -locker ~/.scripts/lock.sh -time 10 -detectsleep &

#Enable numlock
numlockx &

#Show a background
exec ~/.scripts/background.sh &

#Start compton
compton -c -C -b

#Show polybar
exec polybar main &

#Start i3
exec i3
