#Setup XRDB
xrdb $XDG_CONFIG_HOME/xorg/Xresources

#Show a background
exec ~/.scripts/background.sh &

#Set a default volume level
amixer set Master 20%

#Start picom 
picom -c -b

#Show polybar
exec polybar main &

#Start xautolock
xautolock -locker ~/.scripts/lock.sh -time 10 -detectsleep &

#Enable numlock
numlockx &

#Attempt to connect to all bluetooth devices 
exec ~/.scripts/bluetooth.sh &

#Set the default profile
exec ~/.scripts/profiles/laptop.sh &

#Start i3
exec i3
